dist: trusty
language: php
php:
   - hhvm
#language: python
#python:
#  - "pypy3.5"
env:
  global:
  - SCRIPT_PATH=scripts/
# command to install dependencies
# install:
#  - pip install -r requirements.txt

# install custom chrome version
# before_script:
#- wget http://chromedriver.storage.googleapis.com/2.22/chromedriver_linux64.zip
#- unzip chromedriver_linux64.zip $TRAVIS_BUILD_DIR
#- export CHROME_BIN=$TRAVIS_BUILD_DIR/chromium-browser

# command to run tests
#script: 
#- pytest

#- which chrome

# Some PHP Testing
#- which composer
#- $(`which composer`).phar self-update
#- composer self-update

# Update composer?
before_install:
- wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php --
- which composer

install:
- sudo mv -v composer.phar /usr/local/bin/composer

before_script:
- composer self-update
- composer --version

script:
- which composer
- composer --version

# OS Environment Testing
#- nproc --all
#- lscpu
#- python cores.py

# Nested script testing
#before_script: 
#- cd $SCRIPT_PATH
#- pwd
#- chmod +x yello.sh
#script: bash yello.sh 


