--- 
os: linux
arch: arm64-graviton2
virt: lxd
language: python
python: 
  - 3.7
before_install:
  - python -m pip install --upgrade pip
  - pip check
install:
  - pip install --use-feature=2020-resolver -r requirements.txt
script:
  - pip --version
  - pip freeze --local
