language: node_js
os: linux
dist: xenial

notifications:
  email: false
node_js:
  - "10.19.0"
  - "lts/*"
  - stable
  - node

install: npm install

stages:
  - name: lint
  - name: coverage
  - name: release
    if: branch = master && type NOT IN (pull_request)
  - name: docs
    if: branch = master && type NOT IN (pull_request)

jobs:
  include:
    - stage: lint
      script: true
    - stage: coverage
      script: true
    - stage: release
      node_js: node
      deploy:
        provider: script
        cleanup: false
        script: true
    - stage: docs
      script: true
