# default os is Linux (Xenial) and sudo is True
 language: node_js
 node_js:
 - '9'
 language: php
 php:
 - '7.2'
 before_install:
 - sudo apt-get update
 - sudo apt-get install python3
 - rvm install 2.5.3
 - wget https://github.com/mongodb/mongo-php-driver/releases/download/1.5.3/mongodb-1.5.3.tgz
 jobs:
   include:
     - stage: Need sudo?
       script: echo `which python3`
     - stage: MongoDB PHP ext installed?
       script: pecl install -f mongodb-1.5.3.tgz && php -m | grep mongo
# os: osx
# addons:
#  homebrew:
#    packages:
#    - node
#    update: false

