language: node_js
os: linux
dist: xenial

notifications:
  email: false
node_js:
  - "10.19.0"
  - "lts/*"
  - stable
  - node

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: coverage
      script: npm run coverage
    - stage: release
      if: branch = master && type NOT IN (pull_request)
      node_js: node
      deploy:
        provider: script
        cleanup: false
        script: true
    - stage: docs
      if: branch = master && type NOT IN (pull_request)
      script: true
