dist: xenial
language: ruby
cache:
  directories:
    - vendor/cache
install: true
script:
  - if [ ! -d "vendor/cache" ]; then bundle install; fi # first installation if we have no cache else
  - bundle install --local # install from cache
  - bundle cache # and then cache whatever we just installed for subsequent reruns
