os: linux
dist: xenial
language: python
python:
  - 3.7

services:
  - docker

before_install:
  - python3 -m http.server 8080 &

jobs:
  include:
    - name: First Job
      install: true
      script: curl localhost:8080?x=1

    - name: Second Job  
      install: true 
      script: curl localhost:8080?x=2

    - name: Third Job  
      install: true 
      script: curl localhost:8080?x=3
