language: shell
dist: bionic

addons: 
  apt: 
    packages: 
      - postgresql-client-11
  postgresql: "11"
env:
  global:
  - PGPORT=5433
#before_install:
  #- sudo apt-get update
  #- sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  #- sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  #- sudo service postgresql stop
  #- sudo service postgresql start 11
before_script:
  - psql -c "CREATE USER cooklist WITH PASSWORD 'cooklist';" -U postgres
  - psql -c "ALTER USER cooklist CREATEDB;" -U postgres
  - psql -c "ALTER USER cooklist WITH SUPERUSER;" -U postgres
  - psql -c "CREATE DATABASE cooklist WITH OWNER cooklist;" -U postgres
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create extension intarray"  
install: true
script: echo hello
