--- 
compiler: g++
dist: xenial
env: 
  matrix: 
    - TARGET=ARM7
    - TARGET=X86_64
jobs: 
  include: 
    - 
      name: "build $TARGET"
      script: "export TARGET=armv7;sleep 1; echo \"build $TARGET \""
      stage: build
    - 
      name: "Unit Tests"
      script: "sleep 1; echo \"test 1\""
      stage: test
    - 
      name: "Deploy to Github"
      script: "sleep 1; echo \"deploy\""
      stage: deploy
language: cpp
os: linux
stages: 
  - build
  - test
  - deploy
