language: python

python:
  - 3.6

bundler_args: --retry 3

install:
  - sudo apt-get update
  - chmod u+x travis_miniconda.sh
  - ./travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f conda_config.yml
  - source activate conda_tests
  - which python

script:
   - conda --help
   - which python
