language: node_js
matrix:
  include:
    - os: linux-ppc64le
      env: OSARCH=linux-ppc64le
      sudo: required
    - os: linux
      env: OSARCH=linux-amd64
      sudo: required
    - os: linux-s390
      sudo: required
      language: bash
      env: OSARCH=linux
script:
  - jdk_switcher use openjdk10
  - which openjdk
