language: smalltalk
dist: Xenial

os: linux

smalltalk:
  - GemStone-3.5.1
  - Pharo-5.0
  - Squeak-5.1
  - GemStone-2.4.8
  - GemStone-3.1.0.6
  - GemStone-3.2.17
  - GemStone-3.3.9
  - GemStone-3.4.5
  - GemStone-3.5.2
  - Pharo-3.0
  - Pharo-4.0
  - Pharo-6.0
  - Pharo-6.1
  - Squeak-4.5
  - Squeak-4.6
  - Squeak-5.0
  - Squeak-trunk

smalltalk_config:
  - .smalltalkA.ston
  - .smalltalkB.ston

matrix:
  allow_failures:
    - smalltalk: Squeak-4.4
    - smalltalk: Squeak-4.5
    - smalltalk: Squeak-4.6
    - smalltalk: Squeak-5.0
    - smalltalk: Squeak-5.1
    - smalltalk: Squeak-trunk
    - smalltalk: GemStone-2.4.8
    - smalltalk: Pharo-6.1
