notifications:
  webhooks:
    urls:
      https://hooks.glip.com/webhook/3cca150a-f848-b110-ef77f0ce6057
    on_success: always
    on_failure: always
    on_start: always

#language: python
#script:
#- which gpg
#- gpg --list-secret-keys --keyid-format LONG
#- python -c 'import sys; print(sys.byteorder)'
#- gpg --import exported_key.gpg

