language: shell
jobs:
  include:
    - stage: "Install"
      name: "Install Once"
      script: cat "assemble" > one_or_more_generated_files_needed_by_other_jobs.txt
      workspaces:
        create:
          name: assemble_workspace
          paths:
            - one_or_more_generated_files_needed_by_other_jobs.txt
    - stage: "Tests"
      name: "API Tests"
      workspaces:
        use: assemble_workspace
      script:
        - cat "API Tests" >> one_or_more_generated_files_needed_by_other_jobs.txt
        - cat one_or_more_generated_files_needed_by_other_jobs.txt
    - stage: "GUI Tests"
      name: "GUI Tests"
      workspaces:
        use: assemble_workspace
      script: 
        - cat "GUI Tests" >> one_or_more_generated_files_needed_by_other_jobs.txt
        - cat one_or_more_generated_files_needed_by_other_jobs.txt
