dist: bionic
language: python
python: 
  - "3.7"
before_install:
  - apt-get -y remove mysql-server
  - apt-get -y autoremove
  - apt-get -y install software-properties-common
  - add-apt-repository -y ppa:ondrej/mysql-5.6
  - apt-get update
  - apt-get -y install mysql-server
script:
  - which mysql
