language: node_js

node_js:
  - 10
  - "node"

cache:
  yarn: true

install: skip

jobs:
  fast_finish: true
  allow_failures:
    - node_js: "node"
  include:
    - stage: test-renamed
      script: 
        - echo "Explicit test stage"
    - stage: deploy
      node_js:
        - "10.20.1"
      script:
        - echo "Deploy stage"
    - stage: UItest
      node_js:
        - "10.20.1"
      script:
        - echo "UItests stage"
