dist: bionic
language: java
addons:
  apt:
    sources:
      - sourceline: "deb https://apache.bintray.com/couchdb-deb bionic main"
    packages:
    - couchdb
before_script:
  - curl -X PUT localhost:5984/support_debug
script:
  - curl http://admin:password@localhost:5984/support_debug
