language: java
matrix:
  include:
    - os: linux-ppc64le
      env: OSARCH=linux-ppc64le
      sudo: required
    - os: linux
      env: OSARCH=linux-amd64
      sudo: required
    - os: linux-s390
      sudo: required
      language: bash
      env: OSARCH=linux
before_script:
  - nvm install 12.14.1
jdk:
  - oraclejdk9
script:
  - which openjdk
  - node --version
