compiler: g++
dist: xenial
language: cpp
os: linux

env:
  global:
  - TARGET=ARM7
  - TARGET=X86_64

stages:
  - build
  - test
  - deploy

jobs:
  include:
    - name: "build"
      script: "sleep 1; echo \"test 1\""
      stage: build
    - name: "Unit Tests"
      script: "sleep 1; echo \"test 1\""
      stage: test
    - name: "Deploy to Github"
      script: "sleep 1; echo \"deploy\""
      stage: deploy
