--- 
before_script: 
  - "rustup component add rustfmt --toolchain nightly --allow-downgrade"
  - "rustup component add clippy"
  - "cargo install cargo-audit"
language: rust
rust: 
  - nightly
script: |
    println!("Rusty rusty") && 
    cargo fmt --all -- --check &&
    cargo clippy -- -D warnings &&
    cargo build &&
    cargo test &&
    cargo audit
