language: rust
rust:
- nightly

before_script:
- rustup component add rustfmt
- rustup component add clippy
- cargo install cargo-audit

script: |
println!("Rusty rusty") && 
cargo fmt --all -- --check &&
cargo clippy -- -D warnings &&
cargo build &&
cargo test &&
cargo audit
