dist: bionic
language: python
python: 
  - "3.7"
before_install:
  - sudo add-apt-repository -y ppa:ondrej/mysql-5.6
  - sudo apt-get -q update
  - sudo apt-get -y install mysql-server-5.6 mysql-client-core-5.6 mysql-client-5.6
script:
  - which mysql
  - mysql -V
