# default os is Linux (Xenial) and sudo is True
 language: node_js
 node_js:
 - '9'
 language: php
 php:
 - '7.2'
 env:
   global:
   - ext_dir=$(php -r "echo ini_get('extension_dir');")
 cache:
   directories:
    - $ext_dir
 #before_install:
 #- sudo apt-get update
 #- sudo apt-get install python3
 #- rvm install 2.5.3
 jobs:
   include:
    # - stage: Need sudo?
    #   script: echo `which python3`
     - stage: MongoDB PHP ext installed?
       script: |
           if [[ ! -e $ext_dir/mongodb.so ]]; then
             wget https://github.com/mongodb/mongo-php-driver/releases/download/1.5.3/mongodb-1.5.3.tgz
             pecl install -f mongodb-1.5.3.tgz
             echo "extension=mongodb.so" >> $(phpenv prefix)/etc/php.ini
             php -m | grep "mongo"
           fi
     - stage: Clone other repos
       script: |
           git clone https://github.com/inspaya/demo-reverse-proxy.git
           git clone https://github.com/openstack/python-jenkins.git
           git clone https://github.com/inspaya/cerebro.git
# os: osx
# addons:
#  homebrew:
#    packages:
#    - node
#    update: false

