# default os is Linux (Xenial) and sudo is True
language: node_js
node_js:
- '9'
before_install:
- apt-get install python3.6
- rvm install 2.5.3
jobs:
  include:
    - stage: Need sudo?
      script: echo `which python3`

