dist: bionic
language: java
addons:
  apt:
    sources:
      - https://apache.bintray.com/couchdb-deb
    packages:
    - couchdb
before_script:
  - curl -X PUT localhost:5984/support_debug
script:
  - curl localhost:5984/support_debug
