language: java
os: linux
dist: xenial
jdk:
  - openjdk14
script:
  - echo "assemble"
jobs:
  include:
    - stage: "Tests"
      name: "API Tests"
      script: echo "*tests.api*"
    - name: "GUI Tests"
      script: echo "*tests.gui*"
